### ISSUE TITLE
Apply getters and setters on nested objects and array elements

### ISSUE THREAD

**Issue by GEP-JOHNGOUDA-zz** [WebReflection/reactive-props#1]
Hello,

I was inspecting the reactive-props package and wanted to reach out and say thank you for sharing such nice libraries in your repo.
I was trying to reactively listen on a complex object received from the server-side, creating a handler for a nested object patch the 1st level props, but nested object's properties are not getting patched with getters/setters anyway to do it without recursively creating handlers for each nested object?

Also how to handle the addition\deletion of properties to existing state, so lets say I created a handler for an object and later I added a property or deleted one, how to handle such situation?

Thank you.

**Comment by WebReflection** [comment]
For nested reactions you are in charge, and you can use https://github.com/WebReflection/introspected#readme, as example, to invoke the update on changes.

For addition and deletion you are in charge, and you can pass a `new Proxy(state, handler)`.

Both are very ad-hoc and non common cases, but as there are ways to produce the expected result, none of this will be part of this library, as it's out of scope to complicate things for the common pattern it was designed for, but it plays already well along.
